In [8]:
import numpy as np

In [ ]:
#One sided inverse
#Left-Inverse
A = np.array([[1,4],[2,5],[3,6]])
tA = np.transpose(A) #to make it a square matrix
tAA = tA@A #If A is full rank, tAA is a full rank invertible matrix
tAInv = np.linalg.inv(tAA) 
AInv = tAInv@tAA
L = tAInv@tA
print(A, "\n", AInv, L@A)

[[1 4]
 [2 5]
 [3 6]] 
 [[1. 0.]
 [0. 1.]] [[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


In [111]:
def minors(p_M , p_r, p_c):
    retM = np.delete(p_M,p_r,0)
    retM = np.delete(retM,p_c,1)
    
    return(np.linalg.det(retM))

# A = np.random.randint(1,20,9).reshape(3,3)
A = np.array([3,0,2,2,0,-2,0,1,1]).reshape(3,3)
D = np.zeros((A.shape[0],A.shape[1]))
C = np.zeros((A.shape[0],A.shape[1]))
g = 1
for r in range(A.shape[0]):
    for c in range(A.shape[1]):
        D[r,c]=minors(A,r,c)
        C[r,c]= D[r,c]*g
        g = 0-g

print(A)
print(D)
print(C)
invA = np.transpose(C)*(1/np.linalg.det(A))
print(invA)
print(invA@A)


[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]
[[  2.   2.   2.]
 [ -2.   3.   3.]
 [  0. -10.   0.]]
[[ 2. -2.  2.]
 [ 2.  3. -3.]
 [ 0. 10.  0.]]
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3  0. ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.11022302e-16  1.00000000e+00  1.11022302e-16]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]
