In [2]:
import numpy as np

In [3]:
A = np.array([[1,-1],[1,1]])
B = np.array([[1,2,2],[2,1,-2],[-2,2,-1]])
Q1 = A/np.sqrt(2)
Q2 = B/3
print(Q1@Q1.T)
print(Q2@Q2.T)


[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Ex 9-2
r = 4
c = 4
A = np.array(np.random.randint(0,r*c,r*c)).reshape(r,c)
Q_ = np.zeros(A.shape)

print(A)
print()
print()
for lp in range(c):
    if lp==0:
        Q_[:,lp] = A[:,lp]
        continue
    for lp2 in range(lp,1,-1):
        print(lp)
        r=A[:,lp2]
        t=Q_[:,lp2-1]
        print(r,t)


[[ 7  3  5 10]
 [ 9  8 12 10]
 [ 7  2 10  8]
 [ 7 13 10  8]]


2
[ 5 12 10 10] [0. 0. 0. 0.]
3
[10 10  8  8] [0. 0. 0. 0.]
3
[ 5 12 10 10] [0. 0. 0. 0.]


In [67]:
#Ex 9-1

A = np.array(np.random.randint(1,20,16).reshape(4,4))
Q, R = np.linalg.qr(A)
print(np.round(Q.T@Q,5))
print()
print()
print(np.round(Q@Q.T,5))
print()
print()
print(np.round(Q@np.linalg.inv(Q),5))
print()
print()
print(np.round(np.linalg.inv(Q)@Q,5))


[[ 1. -0. -0.  0.]
 [-0.  1. -0. -0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


[[ 1.  0. -0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


[[ 1.  0.  0. -0.]
 [-0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [-0. -0.  0.  1.]]


[[ 1.  0. -0. -0.]
 [ 0.  1. -0.  0.]
 [ 0. -0.  1.  0.]
 [ 0. -0. -0.  1.]]


In [121]:
A = np.random.randint(0,20,36).reshape(6,6)
u,r = np.linalg.qr(A)
U,R = np.linalg.qr(u)
print("A")
print(np.round(A))
print("U")
print(np.round(U))
print("R")
print(np.round(R))
print("u")
print(np.round(u))
print("r")
print(np.round(r))

A
[[19 19  2  7 19  2]
 [ 7 17  3  8 19 17]
 [ 8 11 10 16 18 10]
 [19  0 12 16  5  3]
 [ 6  1 19 10 12 13]
 [16  8  9 14 15  6]]
U
[[-1. -0.  0.  1. -0. -0.]
 [-0. -1. -0. -0. -0.  1.]
 [-0. -0. -0. -1. -0. -1.]
 [-1.  1.  0. -0. -0.  0.]
 [-0.  0. -1.  1.  0.  0.]
 [-0.  0.  0. -0.  1.  0.]]
R
[[ 1.  0.  0.  0.  0. -0.]
 [ 0.  1. -0.  0. -0.  0.]
 [ 0.  0.  1.  0. -0.  0.]
 [ 0.  0.  0.  1. -0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
u
[[-1. -0.  0.  1. -0. -0.]
 [-0. -1. -0. -0. -0.  1.]
 [-0. -0. -0. -1. -0. -1.]
 [-1.  1.  0. -0. -0.  0.]
 [-0.  0. -1.  1.  0.  0.]
 [-0.  0.  0. -0.  1.  0.]]
r
[[-34. -21. -19. -27. -31. -14.]
 [  0. -20.   5.  -0. -18. -10.]
 [  0.   0. -18. -11. -12. -16.]
 [  0.   0.   0.  -8.  -1.  -2.]
 [  0.   0.   0.   0.   2.  -2.]
 [  0.   0.   0.   0.   0.   7.]]
