In [13]:
import numpy as np

In [167]:
M = np.array ([[2,3,4,1],[2,1,3,0],[5,3,-1,-3]])
MtM = M@M.T
tMtM = np.array(MtM).T
M, MtM,tMtM

(array([[ 2,  3,  4,  1],
        [ 2,  1,  3,  0],
        [ 5,  3, -1, -3]]),
 array([[30, 19, 12],
        [19, 14, 10],
        [12, 10, 44]]),
 array([[30, 19, 12],
        [19, 14, 10],
        [12, 10, 44]]))

In [246]:
A = np.arange(9).reshape(3,3)
B = np.array(np.random.randint(-9,9,9)).reshape(3,3)
print(A,"\n","\n", B,"\n","\n",2*(A+B),"\n","\n", 2*A+2*B,"\n","\n", A*2+B*2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 
 [[-2 -6  6]
 [ 2  8  4]
 [-2  0 -6]] 
 
 [[ -4 -10  16]
 [ 10  24  18]
 [  8  14   4]] 
 
 [[ -4 -10  16]
 [ 10  24  18]
 [  8  14   4]] 
 
 [[ -4 -10  16]
 [ 10  24  18]
 [  8  14   4]]


In [14]:
ones = np.ones(16).reshape(4,4)
diag = np.diag([1,4,9,16])
dsqrt = diag**.5
print(ones, "\n", "\n",diag, "\n", "\n",dsqrt, "\n", "\n")
print(ones@diag)
print()
print(diag@ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 
 [[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]] 
 
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]] 
 

[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]

[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]
