In [2]:
import numpy as np
import plotly.express as pt

In [3]:
D = np.random.randint(0,20,9).reshape(3,3)
DD = D@D.T
print(np.sqrt(np.trace(D@D.T)))
print(np.linalg.norm(D))
print(D)
print(np.trace(D))



33.27160951922825
33.27160951922825
[[ 1  7 12]
 [ 5  6 16]
 [18 16  4]]
11


In [ ]:
#the diagonal of a matrix DD.T@DD is defined by the dot product of each of its element
print("D","\n",D,"\n")
print(np.dot(D[0],D[0]))
print(np.dot(D[1],D[1]))
print(np.dot(D[2],D[2]),"\n")
print("D@D.T","\n",D@D.T,"\n")
print("square root of trace (D.T@D)=", np.sqrt(np.trace(D.T@D)))
print("norm =", np.linalg.norm(D))

D 
 [[ 9  9 12]
 [11 10  9]
 [19 10  4]] 

306
302
477 

D@D.T 
 [[306 297 309]
 [297 302 345]
 [309 345 477]] 

square root of trace (D.T@D)= 32.93933818400121
norm = 32.93933818400121


In [ ]:
a = np.array([[1,1,1]
              ,[2,2,2],[3,3,3], [4,4,4]])
print(a)
print(a[0].T@a[0])
print(a[1].T@a[1])
print(a[2].T@a[2])
print(a[3].T@a[3])
print(a@a.T)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
3
12
27
48
[[ 3  6  9 12]
 [ 6 12 18 24]
 [ 9 18 27 36]
 [12 24 36 48]]


In [36]:
#Exercise 6.1
D = np.empty((40,10))
for c in range(10):
    for r in range(40):
        D[r,c]=np.linalg.norm( np.random.randint(0,50,100).reshape(10,10))

Da = np.average(D, axis=1)

pt.line(Da)

In [44]:
#Exercise 6-2
sg = []
c = 100
def frob_dist(a=[], b=[]):
    return np.linalg.norm(a,b.any())

A = np.random.randint(0,50,9).reshape(3,3)
B = np.random.randint(0,50,9).reshape(3,3)
s=1
while c >= 1:
    c = frob_dist(s*A,s*B)
    s = s*0.99
    sg.append(c)

print(c)
pt.line(sg)

0.9911625515104527


In [19]:
#Exercise 6-3
A = np.random.randint(0,20,9).reshape(3,3)
B = np.random.randint(0,20,9).reshape(3,3)

print(A)
print(np.linalg.norm(A))
print(np.sqrt(np.trace(A.T@A)))


[[17 16 11]
 [15  1  4]
 [16  4 15]]
37.48332962798263
37.48332962798263


In [161]:
#Exercise 6-4
A = np.random.randint(0,10,100).reshape(10,10)
S=A
gn = []
# print(A)
n1 = np.linalg.norm(A)
for lp in range(30):
    S = S + (lp/n1 * np.eye(len(A)))
    n2 = np.linalg.norm(S-A)
    gn.append(((n1-n2)/n1))


pt.line(gn)

In [43]:
#Exercise 6-5

A = np.random.randint(0,20,12).reshape(4,3)
B = np.random.randint(1,10,12).reshape(3,4)
# r = np.linspace(1,20,20)
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))
C = A@B
print(np.linalg.matrix_rank(C),"\n","\n", C )

3
3
3 
 
 [[ 99  93  51 272]
 [ 62  54  30 152]
 [126  85  58 293]
 [ 97  48  45 241]]


In [ ]:
#Exercise 6-6

A = np.random.randint(1,10,3).reshape(3,1)
B = np.random.randint(1,10,3).reshape(3,1)
C2 = A@B.T
print(np.linalg.matrix_rank(A+B))
print(np.linalg.matrix_rank(A*B))
print(np.linalg.matrix_rank(C2))
A = np.random.randint(1,10,6).reshape(3,2)
B = np.random.randint(1,10,6).reshape(3,2)
C1=A@B.T
print(np.linalg.matrix_rank(A+B))
print(np.linalg.matrix_rank(A*B))
print(np.linalg.matrix_rank(C1))
A = np.random.randint(1,10,9).reshape(3,3)
B = np.random.randint(1,10,9).reshape(3,3)
C0=A@B
print(np.linalg.matrix_rank(A+B))
print(np.linalg.matrix_rank(A*B))
print(np.linalg.matrix_rank(C0))
print(C2)
print(C1)
print(C0)

#Exercise 6-8
print(np.linalg.matrix_rank(C2.T))
print(np.linalg.matrix_rank(C2.T@C2))
print(np.linalg.matrix_rank(C2@C2.T))

1
1
1
2
2
2
3
3
3
[[ 3  6  1]
 [24 48  8]
 [ 6 12  2]]
[[93 44 51]
 [72 51 54]
 [98 49 56]]
[[136 110 117]
 [131  64  87]
 [175 118 155]]
1
1
1


In [ ]:
#Exercise 6-9

A = np.random.randint(0,10,12).reshape(4,3)
B = np.random.randint(0,10,9).reshape(3,3)
C=A@B
print(np.linalg.matrix_rank(C), C.shape)
for lp in range(0,10000):
    v = np.random.randint(1,10,4)
    D = np.hstack((C,np.asmatrix(v).T))
    if np.linalg.matrix_rank(C) < np.linalg.matrix_rank(D):
        print(C, np.linalg.matrix_rank(C))
        print(D, np.linalg.matrix_rank(D))
    
    break
# Max rank possible in a 4x3 matrix is 3. HSTACKing a vector makes it a 4x4 and therefore increases its chance 
# incrementing its rank

#In the below example, the 4x4 matrix created can have a max rank of 4 only. 
# Thus, adding a vector to make it a 4x5 matrix will not affects its rank as rank-5 is not possible in 4x5 dimension. 

A = np.random.randint(0,10,16).reshape(4,4)
B = np.random.randint(0,10,16).reshape(4,4)
C=A@B
print(np.linalg.matrix_rank(C), C.shape)
for lp in range(0,10000):
    v = np.random.randint(1,10,4)
    D = np.hstack((C,np.asmatrix(v).T))
    if np.linalg.matrix_rank(C) < np.linalg.matrix_rank(D):
        print(C, np.linalg.matrix_rank(C))
        print(D, np.linalg.matrix_rank(D))
    
    break




3 (4, 3)
[[ 98  86  80]
 [108  96  84]
 [136 118 109]
 [ 83  77  80]] 3
[[ 98  86  80   7]
 [108  96  84   3]
 [136 118 109   9]
 [ 83  77  80   2]] 4
4 (4, 4)


In [228]:
xd = []
ys = []
d2 = []
for lp in range(2,30):
    for lp2 in range(100):
        d2 = []
        A = np.random.randint(0,30,(lp+1)*(lp+1)).reshape(lp+1,lp+1)
        A[:,lp] = A[:,lp-1]*2
        d2.append(np.log(np.linalg.det(A)))
    xd.append(np.average(d2))
    ys.append((lp+1)*(lp+1))

pt.scatter(xd, ys)


/tmp/ipykernel_2725/278725131.py:9: RuntimeWarning:

divide by zero encountered in log

/tmp/ipykernel_2725/278725131.py:9: RuntimeWarning:

invalid value encountered in log

