In [1]:
import numpy as np

In [2]:
D = np.random.randint(0,20,9).reshape(3,3)
print(np.sqrt(np.trace(D@D.T)))
print(np.linalg.norm(D))
print(D)


24.819347291981714
24.819347291981714
[[ 2  3  0]
 [ 9  5  6]
 [14 16  3]]


In [3]:
D = np.diag([1,2,3,4,5])
D
print(D@D,"\n","\n",D*D)

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]] 
 
 [[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
