In [2]:
import numpy as np

In [3]:
D = np.random.randint(0,20,9).reshape(3,3)
DD = D@D.T
print(np.sqrt(np.trace(D@D.T)))
print(np.linalg.norm(D))
print(D)
print(np.trace(D))



33.27160951922825
33.27160951922825
[[ 1  7 12]
 [ 5  6 16]
 [18 16  4]]
11


In [ ]:
#the diagonal of a matrix DD.T@DD is defined by the dot product of each of its element
print("D","\n",D,"\n")
print(np.dot(D[0],D[0]))
print(np.dot(D[1],D[1]))
print(np.dot(D[2],D[2]),"\n")
print("D@D.T","\n",D@D.T,"\n")
print("square root of trace (D.T@D)=", np.sqrt(np.trace(D.T@D)))
print("norm =", np.linalg.norm(D))

D 
 [[ 9  9 12]
 [11 10  9]
 [19 10  4]] 

306
302
477 

D@D.T 
 [[306 297 309]
 [297 302 345]
 [309 345 477]] 

square root of trace (D.T@D)= 32.93933818400121
norm = 32.93933818400121


In [ ]:
a = np.array([[1,1,1]
              ,[2,2,2],[3,3,3], [4,4,4]])
print(a)
print(a[0].T@a[0])
print(a[1].T@a[1])
print(a[2].T@a[2])
print(a[3].T@a[3])
print(a@a.T)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
3
12
27
48
[[ 3  6  9 12]
 [ 6 12 18 24]
 [ 9 18 27 36]
 [12 24 36 48]]


In [ ]:
#Exercise 6.1

